version: CI {branch} Build {build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:  
 DEPLOYSECRET:
  secure: 1g5fdzDlx1F/MesIe20QRcuZCW/i35gS7WcbLVlFPwsI70ks4suGkHOHAqz+cGIA
 
pull_requests:
  do_not_increment_build_number: true
init:
- ps: ''
install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/taori/buildscripts/master/appveyor/custom.ps1") | iex
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true  
artifacts:
- path: '.\**\*NugetUnlister*.nupkg'
  name: Release
      
deploy:
- provider: NuGet
  api_key:
    secure: jsytsUi4m7/D25NRZmpxpCYxmtF8uzCC6KXrr3U6wtYInaSXnzwSxNIxVp+OkiHl
  artifact: Release

before_build:
 - ps: dotnet test .\tests\NugetUnlister.UnitTests\NugetUnlister.UnitTests.csproj
  
for:


-
  branches:
    only:
      - dev
  build_script:
   - ps: >-

      $env:projPath = ".\src\NugetUnlister\NugetUnlister.csproj"
      
      $env:prefix = CsProj-GetVersionPrefix $env:projPath
      
      $env:buildId = Custom-GetPaddedBuildNumber
      
      $env:fullVersion = "$($env:prefix)-alpha$($env:buildId)"
      
      Write-Host -ForegroundColor Green "Packing with version $($env:fullVersion)"
    
      dotnet pack $env:projPath -c Release -v m -o .\nupkg -p:Version=$env:fullVersion -p:DebugType=portable
-
  branches:
    only:
      - release 
  build_script:
  
  - ps: >-
  
      $env:projPath = ".\src\NugetUnlister\NugetUnlister.csproj"
      
      $env:prefix = CsProj-GetVersionPrefix $env:projPath
      
      $env:buildId = Custom-GetPaddedBuildNumber
      
      $env:fullVersion = "$($env:prefix).$($env:buildId)"
      
      Write-Host -ForegroundColor Green "Packing with version $($env:fullVersion)"
    
      dotnet pack $env:projPath -c Release -v m -o .\nupkg -p:Version=$env:fullVersion -p:DebugType=portable 
-
  branches:
    only:
      - master 
  #deploy: off
  #artifacts: off
  build_script:
  #- cmd: dotnet build -c Release .\src\NugetUnlister\NugetUnlister.csproj -v m
  - ps: >-
  
      $env:projPath = ".\src\NugetUnlister\NugetUnlister.csproj"
      
      $env:prefix = CsProj-GetVersionPrefix $env:projPath
      
      $env:buildId = Custom-GetPaddedBuildNumber
      
      $env:fullVersion = "$($env:prefix)-beta$($env:buildId)"
      
      Write-Host -ForegroundColor Green "Packing with version $($env:fullVersion)"
    
      dotnet pack $env:projPath -c Release -v m -o .\nupkg -p:Version=$env:fullVersion -p:DebugType=portable 
