version: CI {branch} Build {build}
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
environment:  
 DEPLOYSECRET:
  secure: ozR9OxQlYJFAZfT0+WgueGhAZAoCrcAnn5VN8iPsiqGee+E7zJ6rPuUqQgsdJuNT
 
pull_requests:
  do_not_increment_build_number: true
init:
- ps: ''
install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/taori/buildscripts/master/appveyor/custom.ps1") | iex
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true  
artifacts:
- path: '.\nupkg\**\*.nupkg'
  name: Release
      
deploy:
- provider: NuGet
  api_key:
    secure: ozR9OxQlYJFAZfT0+WgueGhAZAoCrcAnn5VN8iPsiqGee+E7zJ6rPuUqQgsdJuNT
  artifact: Release
  
for:


-
  branches:
    only:
      - dev
  build_script:
   - ps: >-

      $env:projPath = ".\src\NugetUnlister\NugetUnlister.csproj"
      $env:prefix = CsProj-GetVersionPrefix($env:projPath)
      $env:buildId = Custom-GetPaddedBuildNumber()
      $env:fullVersion = "$($env:prefix)-alpha$($env:buildId)"
      
      Write-Host -ForegroundColor Green "Packing with version $($env:fullVersion)"
    
      dotnet pack $env:projPath -c Release -v m -o .\nupkg\ -p:Version=$env:fullVersion -p:DebugType=portable
-
  branches:
    only:
      - release 
  build_script:
  
  - ps: >-
  
      $env:projPath = ".\src\NugetUnlister\NugetUnlister.csproj"
      $env:prefix = CsProj-GetVersionPrefix($env:projPath)
      $env:buildId = Custom-GetPaddedBuildNumber()
      $env:fullVersion = "$($env:prefix).$($env:buildId)"
      
      Write-Host -ForegroundColor Green "Packing with version $($env:fullVersion)"
    
      dotnet pack $env:projPath -c Release -v m -o .\nupkg\ -p:Version=$env:fullVersion -p:DebugType=portable 
-
  branches:
    only:
      - master 
  #deploy: off
  #artifacts: off
  build_script:
  #- cmd: dotnet build -c Release .\src\NugetUnlister\NugetUnlister.csproj -v m
  - ps: >-
  
      $env:projPath = ".\src\NugetUnlister\NugetUnlister.csproj"
      $env:prefix = CsProj-GetVersionPrefix($env:projPath)
      $env:buildId = Custom-GetPaddedBuildNumber()
      $env:fullVersion = "$($env:prefix).$($env:buildId)"
      
      Write-Host -ForegroundColor Green "Packing with version $($env:fullVersion)"
    
      dotnet pack $env:projPath -c Release -v m -o .\nupkg\ -p:Version=$env:fullVersion -p:DebugType=portable 
