# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - dev/*
      - feature/*
      - releases/*
  paths:
    include:
      - src/*
pr:
  branches:
    include:
      - master
  autoCancel: true

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: DotNetCoreCLI@2
    displayName: restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: build
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: test
    inputs:
      command: 'test'
      projects: '**/*.csproj'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: pack beta
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/'))
    inputs:
      command: 'pack'
      packagesToPack: '**/NugetUnlister.csproj'
      configuration: 'Release'
      packDirectory: '$(Build.ArtifactStagingDirectory)\nupkg'
      versioningScheme: 'off'
      buildProperties: 'IncludeSymbols=True;PackAsTool=True;SymbolPackageFormat=snupkg;VersionSuffix=beta$(Build.BuildId)'
      verbosityPack: 'Minimal'

  - task: DotNetCoreCLI@2
    displayName: pack release
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/')
    inputs:
      command: 'pack'
      packagesToPack: '**/NugetUnlister.csproj'
      configuration: 'Release'
      packDirectory: '$(Build.ArtifactStagingDirectory)\nupkg'
      versioningScheme: 'off'
      buildProperties: 'IncludeSymbols=True;PackAsTool=True;SymbolPackageFormat=snupkg'
      verbosityPack: 'Minimal'

  - task: PublishBuildArtifacts@1
    displayName: 'publish artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'nupkg'
      publishLocation: 'Container'