# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - dev/*
      - feature/*
  paths:
    include:
      - src/*
pr:
  branches:
    include:
      - master
  autoCancel: true

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: DotNetCoreCLI@2
    displayName: restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: build
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: test
    inputs:
      command: 'test'
      projects: '**/*.csproj'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: '**/NugetUnlister.csproj'
      configuration: 'Release'
      packDirectory: '$(Build.ArtifactStagingDirectory)\nupkg'
      versioningScheme: 'off'
      buildProperties: 'IncludeSymbols=True;PackAsTool=True'
      verbosityPack: 'Minimal'